language: python

python:
  - 2.7
  - 3.3

cache:
  directories:
    - $HOME/.pip-cache/

env:
  - DJANGO=Django==1.10

install:
  - pip install $DJANGO coverage coveralls pep8 $HOME/.pip-cache

script: coverage run setup.py test

before_script:
    - pep8 --ignore=E501 secure_login/

after_success: coveralls

matrix:
  exclude:
   - python: 3.3
     env: DJANGO=Django==1.4.2
