language: python

python:
    - 2.6
    - 2.7

install:
    - pip install -r requirements.txt
    - pip install pep8

before_script:
    - pep8 --ignore=E501 example/

script: python example/manage.py test secure_login
