language: python

python:
  - 2.7
  - 3.3

cache:
  directories:
    - $HOME/.pip-cache/

env:
  - DJANGO=Django==1.10

install:
  - "pip install -r requirements.txt"

script: coverage run setup.py test

before_script:
    - export DJANGO_SETTINGS_MODULE="secure_login.settings"

after_success: coveralls

matrix:
  exclude:
   - python: 3.3
     env: DJANGO=Django==1.4.2
